{% set name = "flexsweep" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flexsweep-{{ version }}.tar.gz
  sha256: a599798259bb9898a08788492a4a20f1f55fbcfa9fdf645c7a61e541840243b0

build:
  noarch: python
  script: |
    {{ PYTHON }} -m pip install . -vv
    {{ PYTHON }} -m pip install "tensorflow>=2.18.0,<3.0.0" -v
  number: 0

requirements:
  host:
    - python >=3.10,<3.13
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.10,<3.13
    - pip
    - scipy <2.0.0,>=1.14.0
    - scikit-allel <2.0.0,>=1.3.8
    - scikit-learn <2.0.0,>=1.5.1
    - joblib <2.0.0,>=1.4.2
    - threadpoolctl <4.0.0,>=3.5.0
    - click <9.0.0,>=8.1.7
    - numpy ==1.26.4
    - numba <0.61.0,>=0.60.0
    - demes <0.3.0,>=0.2.3
    - pyarrow <18.0.0,>=17.0.0
    - matplotlib-base <4.0.0,>=3.9.2
    - polars <2.0.0,>=1.14.0

test:
  imports:
    - flexsweep
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jmurga/flexsweep
  summary: ''
  license: MIT
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - jmurga
